
// background.js - TubeFetch Service Worker
const BACKEND_URL = 'http://localhost:4000';

/**
 * Generates or retrieves a persistent sessionId shared between background and popup.
 */
async function getSessionId() {
    return new Promise(resolve => {
        chrome.storage.local.get(['sessionId'], (result) => {
            if (result.sessionId) {
                resolve(result.sessionId);
            } else {
                const newId = Math.random().toString(36).substring(2, 15);
                chrome.storage.local.set({ sessionId: newId }, () => resolve(newId));
            }
        });
    });
}

/**
 * Fetches YouTube and Google cookies and formats them in Netscape format.
 */
async function getYoutubeCookies() {
    const domains = [
        ".youtube.com", 
        "www.youtube.com", 
        "music.youtube.com", 
        ".google.com", 
        "accounts.google.com"
    ];
    let allCookies = [];
    
    for (const domain of domains) {
        const cookies = await new Promise(resolve => chrome.cookies.getAll({ domain }, resolve));
        allCookies = allCookies.concat(cookies);
    }
    
    // De-duplicate
    const cookieMap = new Map();
    allCookies.forEach(c => {
        const key = `${c.name}:${c.domain}:${c.path}`;
        if (!cookieMap.has(key)) cookieMap.set(key, c);
    });
    
    const uniqueCookies = Array.from(cookieMap.values());
    let netscape = "# Netscape HTTP Cookie File\n# This file was generated by TubeFetch Background\n\n";
    
    uniqueCookies.forEach(c => {
        let domain = c.domain;
        const includeSub = domain.startsWith('.') ? "TRUE" : "FALSE";
        const path = c.path;
        const secure = c.secure ? "TRUE" : "FALSE";
        const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0;
        const name = c.name;
        const value = c.value;
        netscape += `${domain}\t${includeSub}\t${path}\t${secure}\t${expiry}\t${name}\t${value}\n`;
    });
    
    return netscape;
}

/**
 * Triggers a pre-load of video info in the backend.
 */
async function preloadVideoInfo(url) {
    console.log(`[Background] Pre-loading info for: ${url}`);
    try {
        const [sessionId, cookies] = await Promise.all([getSessionId(), getYoutubeCookies()]);
        
        const response = await fetch(`${BACKEND_URL}/info`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ 
                url: url, 
                cookies: cookies,
                sessionId: sessionId 
            })
        });

        if (response.ok) {
            const data = await response.json();
            console.log(`[Background] Pre-load successful for: ${data.title}`);
        } else {
            console.warn(`[Background] Pre-load failed with status: ${response.status}`);
        }
    } catch (err) {
        console.error(`[Background] Pre-load error:`, err.message);
    }
}

// Listen for tab updates to detect YouTube video navigation
chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
    // Only trigger when the page has finished loading and it's a YouTube video
    if (changeInfo.status === 'complete' && tab.url) {
        if (tab.url.includes('youtube.com/watch') || tab.url.includes('youtu.be/')) {
            preloadVideoInfo(tab.url);
        }
    }
});

// Clean URL helper (same logic as popup.js)
function cleanYouTubeUrl(rawUrl) {
    try {
        const parsed = new URL(rawUrl);
        if (parsed.hostname === 'youtu.be') {
            const videoId = parsed.pathname.slice(1).split('/')[0];
            return `https://www.youtube.com/watch?v=${videoId}`;
        }
        const videoId = parsed.searchParams.get('v');
        if (!videoId) return rawUrl;
        return `https://www.youtube.com/watch?v=${videoId}`;
    } catch {
        return rawUrl;
    }
}
